# -*- coding: utf-8 -*-
"""
Created on Tue May 14 08:19:56 2024

@author: a1147969
"""

#paths
mPath = 'C:/Users/a1147969/Box/#uni/#Projects/waveform/drugs study/dzp_study/' # root folder for study
eeglab_datIn = 'C:/Users/a1147969/Box/#uni/#Projects/waveform/drugs study/dzp_study/eeglab_dat/' # location of eeglab data generated by matlab script
mne_datIn = 'C:/Users/a1147969/Box/#uni/#Projects/waveform/drugs study/dzp_study/mne_dat/' # location of mne files generated by preprocessing.py
grp_dat_path = 'C:/Users/a1147969/Box/#uni/#Projects/waveform/drugs study/dzp_study/group dat/' # location of group data files generated by analysis

cond = ('placebo', 'diazepam')
time = ('PRE', 'POS')

ID = ('001','002','003','004','005','006','009','010','011','012','013','014','015','016','017','018','019','020','021','022','023') 
a_rhy = ('occ', 'mu')

PmaxN = 5
Pheight = 0.1
Pwidth = [1, 8]
specMin = 2
specMax = 40

srate = 1000
nseg = 4000

emd_mask_frq = {'a': [120, 64, 32, 11, 7, 2], 'lb': [60, 30, 20, 10, 2], 'ub': [80, 45, 30, 20, 2]}

imf_pk = {'a':[3], 'lb':[2], 'ub':[2]}

src_out = mPath + 'source/' # location of source files
fsavg_trans_f = 'C:/Users/a1147969/mne_data/MNE-fsaverage-data/fsaverage/bem/fsaverage-trans.fif'
fsavg_fnme = 'C:/Users/a1147969/mne_data/MNE-fsaverage-data/'
fsavg_bemf = 'C:/Users/a1147969/mne_data/MNE-fsaverage-data/fsaverage/bem/'

bands = {'alpha': [7, 14], 'l-beta': [15, 20], 'u_beta': [21, 30]}
lap_chs = {'C4': ['C1' ,'C6', 'CP4', 'FC4'], 'Pz': ['CPz', 'POz', 'P1', 'P2']} 

colors = ['lightpink', 'skyblue']
tme_lab = ['Pre', 'Pos']
cnd_lab = ['Placebo', 'Diazepam']
lobes = {'Temporal':0, 'Occipital':1, 'Sensorimotor':2, 'Parietal':4}

ssd_snr_thresh = {'a_frq':(3.87), 'lb_frq':(2.14), 'ub_frq':(1.95)}

numPCs = 4

ex_waves = {'wave1':{'PC': 1, 'lobe':('Sensorimotor', 2), 'bound':(86, 130)},
	    'wave2':{'PC': 1, 'lobe':('Parietal', 4), 'bound':(91,135)},
	    'wave3':{'PC': 2, 'lobe':('Sensorimotor',2), 'bound':(82, 121)}}

ex_wave_loc_dict = {0:[-0.08, 0, 0.24, 1],
		    1:[0.18, 0, 0.24, 1],
		    2:[0.44, 0, 0.24, 1],
		    3:[0.76, 0, 0.24, 1]}

stat_loc = {0:[-0.03, 0, 0.18, 0.85],
	    1:[0.25, 0, 0.18, 0.85],
	    2:[0.54, 0, 0.18, 0.85],
	    3:[0.82, 0, 0.18, 0.85]}

subs = {'placebo':['001', '002', '003', '004', '005', '006', '010', '014', '015', '017', '018', '019', '020', '021', '023'],
	'diazepam':['002', '003', '004', '005', '006', '009', '014', '015', '016', '017', '019', '020', '021', '022', '023']}


